### ISSUE TITLE
Fried LED - parts list????

### ISSUE THREAD

**Issue by 1bangsnapalaking** [sparkfun/Geiger_Counter#6]
In a hurried attempt to listen to the counter circuit, I connected a speaker between ground and the green LED which fried after blinking a few times. I would like to replace this LED, but can find no reference as to the LED's specs. Please provide details or at least a part number. Thanks!

**Comment by ToniCorinne** [comment]
Hi @1bangsnapalaking - sorry for the lack of info on that. We are actually in the process of updating our Eagle libraries to address some of those issues. 

For now though, the LED datasheet can be found [here](http://optoelectronics.liteon.com/upload/download/DS22-2000-072/S_110_LTST-C150KGKT.pdf), and the part number is LTST-C150KGKT.

Hope that helps!
